name: Security Scan Public Image

on:
  workflow_dispatch:

jobs:
  trivy-scan:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest

    steps:
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      
      - name: Run Trivy vulnerability scanner on a public image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'grpc/csm-o11y-example-python-client'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'
